[tool.ruff]
line-length = 100
select = ["E","F","I","B","UP"]
ignore = ["E501"]

[tool.ruff.isort]
known-first-party = ["api","planners","generators","policy","db","orchestrator"]

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
strict_optional = true
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_configs = true
no_implicit_optional = true
plugins = []
exclude = ["app/", "docs/", "runtime/"]
